//! Standalone visualization window backed by winit.
//!
//! When the `gui` feature is enabled, a wry webview panel is created
//! alongside the 3D viewport for the schema-driven options UI.
//!
//! ```no_run
//! # use viso::Viewer;
//! Viewer::builder()
//!     .with_path("assets/models/4pnk.cif")
//!     .build()
//!     .run()
//!     .unwrap();
//! ```

use std::sync::Arc;
use std::time::Instant;

use winit::application::ApplicationHandler;
use winit::event::{ElementState, MouseScrollDelta, WindowEvent};
use winit::event_loop::{ActiveEventLoop, ControlFlow, EventLoop};
use winit::window::{Window, WindowAttributes, WindowId};

use crate::error::VisoError;
use crate::input::processor::InputProcessor;
use crate::input::{InputEvent, MouseButton};
use crate::options::VisoOptions;
use crate::VisoEngine;

// ── Builder ──────────────────────────────────────────────────────────────

/// Fluent builder for [`Viewer`].
pub struct ViewerBuilder {
    path: Option<String>,
    options: Option<VisoOptions>,
    title: String,
}

impl ViewerBuilder {
    /// Create a builder with sensible defaults (title "Viso", no path,
    /// default options).
    fn new() -> Self {
        Self {
            path: None,
            options: None,
            title: "Viso".into(),
        }
    }

    /// Set the structure file path (`.cif` or `.pdb`).
    #[must_use]
    pub fn with_path(mut self, path: impl Into<String>) -> Self {
        self.path = Some(path.into());
        self
    }

    /// Override the default options.
    #[must_use]
    pub fn with_options(mut self, options: VisoOptions) -> Self {
        self.options = Some(options);
        self
    }

    /// Set the window title.
    #[must_use]
    pub fn with_title(mut self, title: impl Into<String>) -> Self {
        self.title = title.into();
        self
    }

    /// Consume the builder and produce a [`Viewer`].
    #[must_use]
    pub fn build(self) -> Viewer {
        Viewer {
            path: self.path,
            options: self.options,
            title: self.title,
        }
    }
}

// ── Viewer ───────────────────────────────────────────────────────────────

/// A standalone window that displays a protein structure.
///
/// Construct via [`Viewer::builder`], then call [`run`](Self::run) to
/// enter the event loop.
pub struct Viewer {
    path: Option<String>,
    options: Option<VisoOptions>,
    title: String,
}

impl Viewer {
    /// Start a new builder.
    #[must_use]
    pub fn builder() -> ViewerBuilder {
        ViewerBuilder::new()
    }

    /// Open the window and run the event loop. Blocks until the window is
    /// closed.
    ///
    /// # Errors
    ///
    /// Returns [`VisoError::Viewer`] if the event loop or render engine
    /// fails to initialise.
    pub fn run(self) -> Result<(), VisoError> {
        // When the GUI panel is enabled on Linux, force X11 so wry can
        // embed the WebKitGTK webview as a child window (it only accepts
        // Xlib handles).  Without the GUI we stay on native Wayland.
        #[cfg(all(target_os = "linux", feature = "gui"))]
        std::env::set_var("GDK_BACKEND", "x11");

        #[cfg(all(target_os = "linux", feature = "gui"))]
        gtk::init()
            .map_err(|e| VisoError::Viewer(format!("GTK init failed: {e}")))?;

        // Suppress non-fatal X11 errors generated by wry/WebKitGTK
        // (GLXBadWindow, BadWindow, etc.) that would otherwise crash winit.
        #[cfg(all(target_os = "linux", feature = "gui"))]
        winit::platform::x11::register_xlib_error_hook(Box::new(
            |_display, error| {
                let error = error.cast::<x11_dl::xlib::XErrorEvent>();
                let code = unsafe { (*error).error_code };
                // 168 = GLXBadWindow, 170 = wry child-window teardown
                code == 168 || code == 170
            },
        ));

        #[cfg(all(target_os = "linux", feature = "gui"))]
        let event_loop = {
            use winit::platform::x11::EventLoopBuilderExtX11;
            EventLoop::builder()
                .with_x11()
                .build()
                .map_err(|e| VisoError::Viewer(e.to_string()))?
        };
        #[cfg(not(all(target_os = "linux", feature = "gui")))]
        let event_loop =
            EventLoop::new().map_err(|e| VisoError::Viewer(e.to_string()))?;
        event_loop.set_control_flow(ControlFlow::Poll);

        let mut app = ViewerApp {
            window: None,
            engine: None,
            input: InputProcessor::new(),
            last_frame_time: Instant::now(),
            path: self.path,
            options: self.options,
            title: self.title,
            shown: false,
            #[cfg(feature = "gui")]
            panel: crate::gui::panel::PanelController::new(),
            #[cfg(all(target_os = "linux", feature = "gui"))]
            last_gtk_pump: Instant::now(),
        };

        event_loop
            .run_app(&mut app)
            .map_err(|e| VisoError::Viewer(e.to_string()))
    }
}

// ── Winit app ────────────────────────────────────────────────────────────

/// Internal winit application handler.
struct ViewerApp {
    window: Option<Arc<Window>>,
    engine: Option<VisoEngine>,
    input: InputProcessor,
    last_frame_time: Instant,
    path: Option<String>,
    options: Option<VisoOptions>,
    title: String,
    /// Whether the window has been made visible after the first frame.
    shown: bool,
    #[cfg(feature = "gui")]
    panel: crate::gui::panel::PanelController,
    /// Throttle GTK event pumping so it doesn't starve the render loop.
    #[cfg(all(target_os = "linux", feature = "gui"))]
    last_gtk_pump: Instant,
}

/// Compute the wgpu surface size — always the full window dimensions.
///
/// The webview options panel overlays the right edge of the window;
/// the surface must cover the entire window to avoid stretching.
fn viewport_size(inner: winit::dpi::PhysicalSize<u32>) -> (u32, u32) {
    (inner.width.max(1), inner.height.max(1))
}

/// Create a [`VisoEngine`], optionally loading a structure file.
///
/// When `path` is `None`, an empty scene is created (no geometry loaded).
fn create_engine(
    window: Arc<Window>,
    size: (u32, u32),
    scale: f64,
    path: Option<&str>,
) -> Result<VisoEngine, VisoError> {
    if let Some(path) = path {
        pollster::block_on(VisoEngine::new_with_path(window, size, scale, path))
    } else {
        let mut context =
            pollster::block_on(crate::gpu::RenderContext::new(window, size))?;
        if scale < 2.0 {
            context.render_scale = 2;
        }
        VisoEngine::new_empty(context)
    }
}

impl ViewerApp {
    fn handle_resize(&mut self, size: winit::dpi::PhysicalSize<u32>) {
        let (vp_w, vp_h) = viewport_size(size);
        let Some(engine) = &mut self.engine else {
            return;
        };
        engine.resize(vp_w, vp_h);
        #[cfg(feature = "gui")]
        if let Some(window) = &self.window {
            self.panel.apply_layout(window);
        }
    }

    fn handle_scale_factor_changed(&mut self, scale_factor: f64) {
        let Some(window) = &self.window else { return };
        let inner = window.inner_size();
        let Some(engine) = &mut self.engine else {
            return;
        };
        engine.set_surface_scale(scale_factor);
        let (vp_w, vp_h) = viewport_size(inner);
        engine.resize(vp_w, vp_h);
    }

    /// Drain GUI actions, update, render, and push stats.
    fn handle_redraw(&mut self) {
        #[cfg(feature = "gui")]
        if let (Some(window), Some(engine)) = (&self.window, &mut self.engine) {
            self.panel.drain_and_apply(engine, window);
        }

        let now = Instant::now();
        let dt = now.duration_since(self.last_frame_time).as_secs_f32();
        self.last_frame_time = now;

        let Some(engine) = &mut self.engine else {
            return;
        };

        engine.update(dt);

        match engine.render() {
            Ok(()) => {}
            Err(wgpu::SurfaceError::Outdated | wgpu::SurfaceError::Lost) => {
                let Some(w) = &self.window else { return };
                let inner = w.inner_size();
                let (vp_w, vp_h) = viewport_size(inner);
                engine.resize(vp_w, vp_h);
            }
            Err(e) => {
                log::error!("render error: {e:?}");
            }
        }

        #[cfg(feature = "gui")]
        self.panel.push_stats_if_due(now, engine);

        let Some(w) = &self.window else { return };

        #[cfg(feature = "gui")]
        self.panel.tick_slide(dt, w);

        w.request_redraw();
    }

    // ── Input event handlers ────────────────────────────────────────

    /// Forward a mouse/scroll/modifier event through the InputProcessor
    /// and execute any resulting command.
    fn dispatch_input(&mut self, event: InputEvent) {
        let Some(engine) = &mut self.engine else {
            return;
        };
        // Update cursor position for GPU picking
        if let InputEvent::CursorMoved { x, y } = event {
            engine.gpu.cursor_pos = (x, y);
        }
        if let Some(cmd) =
            self.input.handle_event(event, engine.hovered_target())
        {
            let _ = engine.execute(cmd);
        }
    }

    fn handle_mouse_input(
        &mut self,
        button: winit::event::MouseButton,
        state: ElementState,
    ) {
        let pressed = state == ElementState::Pressed;
        self.dispatch_input(InputEvent::MouseButton {
            button: MouseButton::from(button),
            pressed,
        });
    }

    fn handle_cursor_moved(
        &mut self,
        position: winit::dpi::PhysicalPosition<f64>,
    ) {
        #[allow(clippy::cast_possible_truncation)]
        self.dispatch_input(InputEvent::CursorMoved {
            x: position.x as f32,
            y: position.y as f32,
        });

        let Some(window) = &self.window else { return };
        #[cfg(feature = "gui")]
        self.panel
            .update_peek(position.x as f32, position.y as f32, window);
        window.request_redraw();
    }

    fn handle_mouse_wheel(&mut self, delta: MouseScrollDelta) {
        #[allow(clippy::cast_possible_truncation)]
        let scroll_delta = match delta {
            MouseScrollDelta::LineDelta(_, y) => y,
            MouseScrollDelta::PixelDelta(pos) => pos.y as f32 * 0.01,
        };
        self.dispatch_input(InputEvent::Scroll {
            delta: scroll_delta,
        });
        let Some(w) = &self.window else { return };
        w.request_redraw();
    }

    fn handle_modifiers_changed(&mut self, modifiers: winit::event::Modifiers) {
        self.dispatch_input(InputEvent::ModifiersChanged {
            shift: modifiers.state().shift_key(),
        });
    }

    fn handle_keyboard_input(&mut self, event: &winit::event::KeyEvent) {
        if event.state != ElementState::Pressed {
            return;
        }
        use winit::keyboard::{KeyCode, PhysicalKey};
        let PhysicalKey::Code(code) = event.physical_key else {
            return;
        };

        #[cfg(feature = "gui")]
        if code == KeyCode::Backslash {
            self.panel.toggle();
            if let Some(window) = &self.window {
                self.panel.apply_layout(window);
            }
            return;
        }

        let Some(engine) = &mut self.engine else {
            return;
        };

        let key_str = format!("{code:?}");
        if let Some(cmd) = self.input.handle_key_press(&key_str) {
            let _ = engine.execute(cmd);
        }
    }
}

/// Build the window attributes, sizing to 75% of the primary monitor.
fn window_attrs(event_loop: &ActiveEventLoop, title: &str) -> WindowAttributes {
    let mut attrs = Window::default_attributes()
        .with_title(title)
        .with_visible(false);

    let monitor = event_loop
        .primary_monitor()
        .or_else(|| event_loop.available_monitors().next());

    if let Some(mon) = &monitor {
        let mon_size = mon.size();
        let scale = mon.scale_factor();
        #[allow(clippy::cast_possible_truncation)]
        let logical_w = (mon_size.width as f64 / scale * 0.75) as u32;
        #[allow(clippy::cast_possible_truncation)]
        let logical_h = (mon_size.height as f64 / scale * 0.75) as u32;
        attrs = attrs.with_inner_size(winit::dpi::LogicalSize::new(
            logical_w, logical_h,
        ));
    }

    attrs
}

impl ApplicationHandler for ViewerApp {
    fn resumed(&mut self, event_loop: &ActiveEventLoop) {
        if self.window.is_some() {
            return;
        }

        let window = match event_loop
            .create_window(window_attrs(event_loop, &self.title))
        {
            Ok(w) => Arc::new(w),
            Err(e) => {
                log::error!("Failed to create window: {e}");
                event_loop.exit();
                return;
            }
        };

        let inner = window.inner_size();
        let scale = window.scale_factor();
        let (vp_w, vp_h) = viewport_size(inner);

        let mut engine = match create_engine(
            window.clone(),
            (vp_w, vp_h),
            scale,
            self.path.as_deref(),
        ) {
            Ok(e) => e,
            Err(e) => {
                log::error!("Failed to initialize engine: {e}");
                event_loop.exit();
                return;
            }
        };

        if let Some(opts) = self.options.take() {
            engine.set_options(opts);
        }

        engine.sync_scene_to_renderers(std::collections::HashMap::new());

        // Render the first frame while the window is still hidden,
        // then reveal it so the user never sees a blank rectangle.
        engine.update(0.0);
        let _ = engine.render();
        window.set_visible(true);
        self.shown = true;

        #[cfg(feature = "gui")]
        self.panel.init_webview(
            window.as_ref(),
            inner.width,
            inner.height,
            &engine,
        );

        window.request_redraw();
        self.window = Some(window);
        self.engine = Some(engine);
    }

    fn window_event(
        &mut self,
        event_loop: &ActiveEventLoop,
        _id: WindowId,
        event: WindowEvent,
    ) {
        if matches!(event, WindowEvent::CloseRequested) {
            event_loop.exit();
            return;
        }

        // Guard: both window and engine must be initialised.
        if self.window.is_none() || self.engine.is_none() {
            return;
        }

        match event {
            WindowEvent::Resized(size) => self.handle_resize(size),
            WindowEvent::ScaleFactorChanged { scale_factor, .. } => {
                self.handle_scale_factor_changed(scale_factor);
            }
            WindowEvent::RedrawRequested => self.handle_redraw(),
            WindowEvent::MouseInput { button, state, .. } => {
                self.handle_mouse_input(button, state);
            }
            WindowEvent::CursorMoved { position, .. } => {
                self.handle_cursor_moved(position);
            }
            WindowEvent::MouseWheel { delta, .. } => {
                self.handle_mouse_wheel(delta);
            }
            WindowEvent::ModifiersChanged(modifiers) => {
                self.handle_modifiers_changed(modifiers);
            }
            WindowEvent::KeyboardInput { event, .. } => {
                self.handle_keyboard_input(&event);
            }
            _ => (),
        }
    }

    #[cfg(all(target_os = "linux", feature = "gui"))]
    fn about_to_wait(&mut self, _event_loop: &ActiveEventLoop) {
        use std::time::Duration;
        // Throttle GTK event pumping to ~60 Hz so it doesn't compete
        // with the render loop (which runs via ControlFlow::Poll).
        let now = Instant::now();
        if now.duration_since(self.last_gtk_pump) >= Duration::from_millis(16) {
            self.last_gtk_pump = now;
            while gtk::events_pending() {
                let _ = gtk::main_iteration_do(false);
            }
        }
    }
}
